### ISSUE TITLE
Error Log 27.12.2014

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/AncientRPG#135]
[09:17:19 WARN]: java.lang.NullPointerException
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.SpellInformationObject.getPartyMembers(SpellInformationObject.java:432)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Parameters.PartyMembersParameter.parseParameter(PartyMembersParameter.java:40)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Parameter.parseParameter(Parameter.java:127)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Command.executeCommand(Command.java:51)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:450)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Command.executeCommand(Command.java:63)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:450)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Command.executeCommand(Command.java:63)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:450)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.IfSection.executeCommand(IfSection.java:65)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:450)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.IfSection.executeCommand(IfSection.java:65)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:450)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Command.executeCommand(Command.java:63)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:450)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Spell.execute(Spell.java:670)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Commands.CommandPlayer.scheduleSpell(CommandPlayer.java:24)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Classes.Commands.ClassCastCommand.processCast(ClassCastCommand.java:66)
[09:17:19 WARN]:        at com.ancientshores.AncientRPG.Listeners.AncientRPGPlayerListener.onPlayerInteract(AncientRPGPlayerListener.java:447)
[09:17:19 WARN]:        at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
[09:17:19 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:17:19 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[09:17:19 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
[09:17:19 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[09:17:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[09:17:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[09:17:19 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:216)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.PlayerInteractManager.interact(PlayerInteractManager.java:374)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:629)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469)
[09:17:19 WARN]:        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)

Ich kann nicht sagen wer was wann wie und wo dieser error produziert wurde.

**Comment by FroznMine** [comment]
Hast du noch ein Stück mehr StackTrace? Meistens steht vor dem StackTrace der Fehlertyp. Könnte helfen bei der Behebung.

**Comment by MysticCity** [comment]
öhm nein... seid wann kopiert pastebin denn nicht alles

**Comment by FroznMine** [comment]
Sollte gefixt sein. Bleibt aber noch auf, bis dass mit dem gesamten Multiworld-Code in die Haupt-Repo kommt.
